name: BuildBack

on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: check
        run: ./Backend/gradlew check